[package]
name = "bevy_net"
version = "0.14.0-dev"
edition = "2021"

[dependencies]
bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
bevy_tasks = { path = "../bevy_tasks", version = "0.14.0-dev" }
bevy_asset = { path = "../bevy_asset", version = "0.14.0-dev" }
bevy_core = { path = "../bevy_core", version = "0.14.0-dev" }
bevy_app = { path = "../bevy_app", version = "0.14.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.14.0-dev" }
bytes = "1.6.0"
bevy_time = { path = "../bevy_time", version = "0.14.0-dev" }

static_init = "1.0.3"

#version used by quinn as of 0.11.2
rustls = { version = "0.23.5", optional = true }

quinn = { version = "0.11.2", optional = true, features = ["rustls"] }

[features]
default = []

Udp = []
Tcp = []
QUIC = ["quinn", "rustls"]

[lints]
workspace = true
