[package]
name = "bevy_net"
version = "0.14.0-dev"
edition = "2021"

[dependencies]
bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
bevy_internal = { path = "../bevy_internal", version = "0.14.0-dev" }
async-net = "2.0.0"
static_init = "1.0.3"


wtransport = "0.1.13"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["WebTransport"] }

serde = "1.0.203"
bytemuck = "1.16.0"
[lints]
workspace = true
