[package]
name = "bevy_net"
version = "0.14.0-dev"
edition = "2021"

[dependencies]
bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
bevy_internal = { path = "../bevy_internal", version = "0.14.0-dev" }
bevy_asset = { path = "../bevy_asset", version = "0.14.0-dev" }
bevy_core = {path = "../bevy_core", version = "0.14.0-dev" }
array-init = "2.1.0"


quinn = { version = "0.11.2", optional = true }
async-net = { version = "2.0.0" , optional = true }

[features]

Udp = ["async-net"]
Tcp = ["async-net"]
QUIC = ["quinn"]


[lints]
workspace = true
