[package]
name = "bevy_net"
version = "0.14.0-dev"
edition = "2021"

[dependencies]
bevy_ecs = { path = "../bevy_ecs", version = "0.14.0-dev" }
bevy_internal = { path = "../bevy_internal", version = "0.14.0-dev" }
async-net = "2.0.0"
static_init = "1.0.3"
cfg-if = "1.0.0"


serde = "1.0.203"


quinn = { version = "0.11.2", optional = true }

[features]

Udp = []
Tcp = []
QUIC = ["quinn"]


[lints]
workspace = true
