[package]
name = "bevy_net"
version = "0.14.0-dev"
edition = "2021"

[dependencies]
bevy_tasks = { path = "../bevy_tasks", version = "0.14.0-dev" }
static_init = "1.0.3"

async-lock = { version = "3.4.0", optional = true }

#same versions as used by quinn to reduce compile times, we can update these as quinn updates.
bytes = "1.0"
rustls = { version = "0.23.0", optional = true, features = ["ring", "std"], default-features = false }
quinn = { version = "0.11.2", optional = true, features = ["log", "platform-verifier"] }

[features]
default = []

tls = ["quinn?/rustls", "quinn?/ring", "dep:rustls"]
quic = ["dep:quinn", "dep:async-lock"]

[lints]
workspace = true
